### ISSUE TITLE
PDF.go not working. 

### ISSUE THREAD

**Issue by joanbono** [datatogether/pdf#5]
Guys, still not working. (Issue related to #3 )

The error is importing the unidoc module.

In pdf.go, I have changed the imports:

~~~go
// pdf extracts metadata from pdf files
package pdf

import (
	"bytes"
	"github.com/datatogether/xmp"
	unicommon "github.com/unidoc/unidoc/common"
	unilicense "github.com/unidoc/unidoc/common/license"
	pdf "github.com/unidoc/unidoc/pdf/lib"
	"io"
~~~

instead of:

~~~go
// pdf extracts metadata from pdf files
package pdf

import (
	"bytes"
	"github.com/datatogether/xmp"
	unicommon "github.com/unidoc/unidoc/common" 
	unilicense "github.com/unidoc/unidoc/license"
	pdf "github.com/unidoc/unidoc/pdf"
	"io"
~~~

But the `unidoc/pdf` contains other folder inside.

When I try to run:

~~~bash
go run main.go
# github.com/datatogether/pdf
../../../go/src/github.com/datatogether/pdf/pdf.go:53:26: invalid operation: (*dict)["Type"] (type core.PdfObjectDictionary does not support indexing)
../../../go/src/github.com/datatogether/pdf/pdf.go:58:23: cannot range over *dict (type core.PdfObjectDictionary)
~~~

**Comment by b5** [comment]
can you try running: `go get -u github.com/datatogether/xmp` and then re-running? I'd forgotten to mention that to ship a fix I had to update the xmp package.

**Comment by joanbono** [comment]
The main problem persists.

The problem is that the unidoc folder tree has changed inside the `pdf` directory I guess.

And also, from `pdf.go`:

~~~go
unilicense "github.com/unidoc/unidoc/license"
~~~

Needs to be changed to:

~~~go
unilicense "github.com/unidoc/unidoc/common/license"
~~~

In order to use the actual folder tree.

My go program:

~~~go
package main

import (
  "github.com/datatogether/pdf"
  //"github.com/datatogether/xmp"
  //"github.com/unidoc/unidoc/pdf/TEST"
  //"github.com/datatogether/xmp"
  //"testing"
  "fmt"
)

func main(){
  meta, err := MetadataForFile("test.pdf")
  fmt.Println(meta)
}
~~~

And when running:

~~~bash
go run .\pdf.go
# github.com/datatogether/pdf
..\go\src\github.com\datatogether\pdf\pdf.go:53:26: invalid operation: (*dict)["Type"] (type core.PdfObjectDictionary does not support indexing)
..\go\src\github.com\datatogether\pdf\pdf.go:58:23: cannot range over *dict (type core.PdfObjectDictionary)
~~~

**Comment by joanbono** [comment]
Hi @b5, any updates on this?

**Comment by joanbono** [comment]
Answered on #6 : 

It seems like is working now, the error no longer appears.

But, for example, for this test program I made:

~~~go
package main

import (
	pdf "github.com/datatogether/pdf"
	"fmt"
)

func main() {
	meta, _ := pdf.MetadataForFile("test.pdf")
	fmt.Println(meta)
}
~~~

When executing:

~~~bash
jbono@MacBook [~/Desktop]> go run main.go
map[]
~~~

Is empty, maybe I'm missing something.

**Comment by b5** [comment]
So, I don't think you're missing anything. The underlying library we're using (unidoc) has changed a fair amount since this package was last updated. I'm currently preoccupied with other projects, which is making it tough to update this package to the degree that I'd like, but we have a project coming up in the next 1-2 weeks that needs PDF metadata _and full text_ extraction. I intend to add those features here.

So, if you can sit tight for a week or two, I'll be shipping updates that make that map actually spit out something useful 😄.

**Comment by joanbono** [comment]
Any updates on this, @b5 ?

**Comment by joanbono** [comment]
@dcwalk @b5 Any updates on this?

**Comment by joanbono** [comment]
Metadata extraction: https://github.com/unidoc/unidoc-examples/blob/master/pdf/metadata/pdf_metadata_get_docinfo.go
